export const aboutPetsimc = "O Programa de Educação Tutorial (PET) é um programa criado pelo Ministério da Educação com objetivo de estimular atividades de pesquisa, ensino e extensão universitárias, no nível de graduação. Os grupos PET trabalham de maneira coletiva e interdisciplinar, sendo compostos por um conjunto de alunos bolsistas e não-bolsistas que trabalham sobre a coordenação de um professor tutor.";

export const objectivesPetsimc = "Desenvolver atividades acadêmicas em padrões de qualidade de excelência; Contribuir para a elevação da qualidade da formação acadêmica dos alunos de graduação; Estimular a formação de profissionais e docentes de elevada qualificação técnica, científica, tecnológica e acadêmica; Estimular o espírito crítico, bem como a atuação profissional pautada pela cidadania e pela função social da educação superior.";

export const joinPetsimc = "Para ingressar no PET, os interessados devem ficar atentos aos editais de seleção. Esses editais são amplamente divulgados na página do PETSIMC, nos canais de comunicação do curso e da própria Universidade Federal de Uberlândia. Após ser aprovado, o aluno deve dedicar-se 20 horas semanais ao cumprimento das atividades de ensino, pesquisa e extensão planejadas pelo grupo.";

export const pillarsPetsimc = "Os pilares do PET é composto por pesquisa, ensino e extensão. O pilar de pesquisa busca a materialização de novos conhecimentos através de novos estudos como iniciações científicas. O pilar de ensino visa construir conhecimento dentro da própria instituição, onde pode ocorrer através de aulas de reforço, monitorias e outros projetos semelhantes. Por fim, o pilar de extensão está relacionado a projetos que envolvem a comunidade externa a faculdade, estimulando uma troca de conhecimento entre a comunidade externa e interna.";

export const membersPetsimc = "Os membros atuais do PET são jovens talentosos e dedicados que estão comprometidos em se desenvolver profissionalmente e em contribuir para a comunidade. Eles vêm de uma ampla gama de background acadêmicos e profissionais e estão interessados em aprender e crescer em uma ampla gama de áreas.";

export const exMembersPetsimc = "Os ex-membros do PET (Programa de Educação Tutorial) são indivíduos talentosos e bem-sucedidos que passaram pelo programa e agora estão seguindo suas carreiras em uma ampla gama de áreas. Eles são orgulhosos de sua associação com o PET e continuam a ser fortemente ligados à comunidade e à missão do programa.";

export const tutorPetsimc = "O tutor atual do PET é uma pessoa altamente capacitada e experiente, com vasto conhecimento e habilidades em sua área de especialização e outras. Ele é responsável por orientar e apoiar os membros atuais do programa, ajudando-os a se desenvolver profissionalmente e a atingir seus objetivos acadêmicos e pessoais.";

export const exTutorsPetsimc = "O ex-tutor do PET é uma pessoa talentosa e bem-sucedida que serviu como mentor e guia para os membros do programa durante sua época como tutor. Durante seu tempo como tutor, demonstrou uma paixão incomparável pela educação e pelo desenvolvimento dos membros do programa. Ajudou muitos a alcançarem seus objetivos acadêmicos e pessoais, e deixou uma marca duradoura na comunidade do PET.";