export const aboutPetsimc = "O Programa de Educação Tutorial (PET) é um programa criado pelo Ministério da Educação com objetivo de estimular atividades de pesquisa, ensino e extensão universitárias, no nível de graduação. Os grupos PET trabalham de maneira coletiva e interdisciplinar, sendo compostos por um conjunto de alunos bolsistas e não-bolsistas que trabalham sobre a coordenação de um professor tutor.";

export const objectivesPetsimc = "Desenvolver atividades acadêmicas em padrões de qualidade de excelência; Contribuir para a elevação da qualidade da formação acadêmica dos alunos de graduação; Estimular a formação de profissionais e docentes de elevada qualificação técnica, científica, tecnológica e acadêmica; Estimular o espírito crítico, bem como a atuação profissional pautada pela cidadania e pela função social da educação superior.";

export const joinPetsimc = "Para ingressar no PET, os interessados devem ficar atentos aos editais de seleção. Esses editais são amplamente divulgados na página do PETSIMC, nos canais de comunicação do curso e da própria Universidade Federal de Uberlândia. Após ser aprovado, o aluno deve dedicar-se 20 horas semanais ao cumprimento das atividades de ensino, pesquisa e extensão planejadas pelo grupo.";

export const pillarsPetsimc = "Os pilares do PET é composto por pesquisa, ensino e extensão. O pilar de pesquisa busca a materialização de novos conhecimentos através de novos estudos como iniciações científicas. O pilar de ensino visa construir conhecimento dentro da própria instituição, onde pode ocorrer através de aulas de reforço, monitorias e outros projetos semelhantes. Por fim, o pilar de extensão está relacionado a projetos que envolvem a comunidade externa a faculdade, estimulando uma troca de conhecimento entre a comunidade externa e interna.";

export const membersPetsimc = "Os membros atuais do PET são jovens talentosos e dedicados que estão comprometidos em se desenvolver profissionalmente e em contribuir para a comunidade. Eles vêm de uma ampla gama de background acadêmicos e profissionais e estão interessados em aprender e crescer em uma ampla gama de áreas.";

export const exMembersPetsimc = "Os ex-membros do PET (Programa de Educação Tutorial) são indivíduos talentosos e bem-sucedidos que passaram pelo programa e agora estão seguindo suas carreiras em uma ampla gama de áreas. Eles são orgulhosos de sua associação com o PET e continuam a ser fortemente ligados à comunidade e à missão do programa.";

export const tutorPetsimc = "O tutor atual do PET é uma pessoa altamente capacitada e experiente, com vasto conhecimento e habilidades em sua área de especialização e outras. Ele é responsável por orientar e apoiar os membros atuais do programa, ajudando-os a se desenvolver profissionalmente e a atingir seus objetivos acadêmicos e pessoais.";

export const exTutorsPetsimc = "O ex-tutor do PET é uma pessoa talentosa e bem-sucedida que serviu como mentor e guia para os membros do programa durante sua época como tutor. Durante seu tempo como tutor, demonstrou uma paixão incomparável pela educação e pelo desenvolvimento dos membros do programa. Ajudou muitos a alcançarem seus objetivos acadêmicos e pessoais, e deixou uma marca duradoura na comunidade do PET.";

export const newsText = "O PET-SIMC, grupo PET respectivo ao curso de Sistemas de Informação do campus de Monte Carmelo da Universidade Federal de Uberlândia, disponibiliza uma coletânea de notícias associadas a universidade, ao grupo, ou a projetos ou acontecimentos relevantes a comunidade.";

export const projectsText = "O PET-SIMC, grupo PET respectivo ao curso de Sistemas de Informação do campus de Monte Carmelo da Universidade Federal de Uberlândia, possuí uma coletânea de projetos próprios e auxílios a projetos já estabelecidos dentro da universidade, prestando apoio ou gerenciando o desenvolvimento das atividades.";

export const aboutText = "O PET-SIMC, grupo PET respectivo ao curso de Sistemas de Informação do campus de Monte Carmelo da Universidade Federal de Uberlândia, disponibiliza algumas informações pertinentes ao grupo sobre sua composição, objetivos e matrizes.";

export const localityText = "O PET-SIMC atualmente dispõe de uma sala localizada na Universidade Federal de Uberlândia, no campus Monte Carmelo, na sala 1B206.";

export const aboutContent = "O Programa de Educação Tutorial (PET) é um programa criado pelo Ministério da Educação com objetivo de estimular atividades de pesquisa, ensino e extensão universitárias, no nível de graduação. Os grupos PET trabalham de maneira coletiva e interdisciplinar, sendo compostos por um conjunto de alunos bolsistas e não-bolsistas que trabalham sobre a coordenação de um professor tutor.\n\nO PET-SIMC é o grupo PET Institucional respectivo ao curso de Sistemas de Informação do campus de Monte Carmelo da Universidade Federal de Uberlândia. Sendo ele um PET Institucional o vínculo do grupo se dá diretamente a UFU, propiciando, sob a orientação de um tutor, a realização de atividades extracurriculares que complementam a formação acadêmica do estudante e atenda necessidades do curso de graduação.\n\nO grupo é composto por um tutor, sendo ele parte do corpo docente da universidade, e até doze membros do corpo discente do curso de Sistemas de Informação no Campus de Monte Carmelo, engajando em atividades como o desenvolvimento de pesquisas acadêmicas, projetos próprios e auxílio a projetos da instituição e a atuação do PET-SIMC está diretamente ligada aos três pilares do ensino superior sendo eles Pesquisa, Ensino e Extensão.";

export const pillarsContent = "Os três pilares, Pesquisa, Ensino e Extensão, são a base do conhecimento acadêmico e do ensino superior no Brasil, compondo o currículo de todos os cursos de graduação, onde a constituição brasileira estabelece que as universidades devem obedecer ao princípio de indissociabilidade entre ensino, pesquisa e extensão.\n\nO pilar Pesquisa se refere a ações desenvolvidas com o intuito de estimular atividades de pesquisa dentro da universidade, ocorrendo geralmente através de monografias, TCCs ou iniciações científicas. No caso dos grupos PET esse pilar é atendido através da obrigatoriedade de desenvolvimento de iniciações científicas por todos os membros vigentes do grupo.\n\nO pilar Ensino está relacionado às atividades voltadas ao aprendizado dos alunos, como horas destinadas às aulas teóricas, práticas, atividades de monitoria, entre outros. No caso do grupo PET esse pilar é atendido através de atividades como monitoria, aulas de reforço, produção de vídeo-aulas, entre outros.\n\nO pilar Extensão tem como objetivo criar uma relação entre a comunidade externa e a universidade, onde são desenvolvidas ações que permitam uma troca de conhecimentos e um vínculo entre as duas comunidades podendo ocorrer através de projetos, orientações, palestas, entre outros. No caso do grupo PET esse pilar é atendido através da participação em projetos de extensão da universidade e a criação de projetos próprios voltados para comunidade externa."

export const historyText = "O PET-SIMC, grupo PET respectivo ao curso de Sistemas de Informação do campus de Monte Carmelo da Universidade Federal de Uberlândia, disponibiliza um breve resumo sobre a história do começo e do desenvolvimento do grupo até atualmente.";

export const historyContent = "O PETSIMC teve sua fundação oficializada em abril de 2020, durante a pandemia do COVID-19. Em 2020 e 2021 enfrenamos o desafio de organizar o grupo e suas atividades de maneira online devido a impossibilidade de atividades presenciais atendendo às diretrizes estabelecidas pela OMS.\n\nEm 2022 tivemos o retorno dos alunos às dependências físicas da universidade, levando a uma necessidade de reestruturação e reorganização do grupo nesse novo contexto que permitia uma nova gama de possibilidades e necessidades.\n\nEm 2023 ocorreu a troca do tutor que fundou o PETSIMC, devido a uma mudança de cidade, onde até o início do ano ele estava à frente do PET de forma remota até o edital para seleção de um novo tutor. Agora com um novo tutor do PETSIMC, veio com ele uma renovação do grupo, com novas ideias e uma nova forma de comandar o programa, o grupo durante esse período passou por uma nova reforma interna na maneira como os membros atenderiam aos três pilares fundamentais do ensino superior e como o grupo interagiria com a comunidade interna e externa, levando ao estabelecimento de uma identidade visual do grupo.\n\nNo final do primeiro semestre de 2023 ocorre uma nova troca devivo a transferência do até então tutor e esse então sai da UFU, mantendo o auxílio ao PETSIMC durante o estabelecimento de um tutor temporário. O grupo se manteve com um tutor temporário, o atual coordenador do curso, até a criação de um novo edital e a oficialização de um novo tutor.\n\nNa metade do segundo semestre de 2023 é oficializado a entrada do novo tutor e uma outra maneira de comandar o PET. Vale ressaltar que nesse ano também houve uma grande rotatividade de membros mais antigos, por terem se formado ou focaram na busca por estágios. Nesse sentido, tivemos um período desafiador repleto de mudanças constantes de membros e tutores.";